package plugin

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/go-github/v60/github"
	log "github.com/sirupsen/logrus"
)

// createCanaryFailureIssue creates a GitHub issue for canary failures
// Note: Issue content generation is now delegated to the A2A agent
func createCanaryFailureIssue(logsBlob, analysisText, baseBranch, githubURL string) error {
	owner, repo, parseErr := extractOwnerRepoFromURL(githubURL)
	if parseErr != nil {
		return fmt.Errorf("failed to extract owner/repo from URL: %v", parseErr)
	}

	// Use simple, descriptive issue content
	// The A2A agent should have already created detailed analysis
	issueTitle := "🚨 Canary Deployment Failed - AI Analysis"
	issueBody := generateIssueBody(logsBlob, analysisText)

	// Create issue using GitHub API with token from Kubernetes secret
	return createGitHubIssue(owner, repo, issueTitle, issueBody)
}

// generateIssueBody generates a GitHub issue body
func generateIssueBody(logsBlob, analysisText string) string {
	return fmt.Sprintf(`## 🚨 Canary Deployment Failure

### Analysis
%s

### Logs
<details>
<summary>Click to view logs</summary>

`+"```"+`
%s
`+"```"+`

</details>

### Next Steps
1. Review the analysis above
2. Check the logs for specific error patterns
3. Consider rolling back the canary deployment
4. Investigate the root cause before retrying

---
*This issue was automatically generated by the Argo Rollouts AI Metric Plugin*`, analysisText, truncate(logsBlob, 10000))
}

// extractOwnerRepoFromURL extracts owner and repository from GitHub URL
func extractOwnerRepoFromURL(githubURL string) (string, string, error) {
	// Remove trailing slash and .git if present
	url := strings.TrimSuffix(githubURL, "/")
	url = strings.TrimSuffix(url, ".git")

	// Split by "/" and get the last two parts
	parts := strings.Split(url, "/")
	if len(parts) < 2 {
		return "", "", fmt.Errorf("invalid GitHub URL format: %s", githubURL)
	}

	owner := parts[len(parts)-2]
	repo := parts[len(parts)-1]

	if owner == "" || repo == "" {
		return "", "", fmt.Errorf("could not extract owner/repo from URL: %s", githubURL)
	}

	return owner, repo, nil
}

// createGitHubIssue creates a GitHub issue using the API
func createGitHubIssue(owner, repo, title, body string) error {
	githubToken, err := getSecretValue("argo-rollouts", "github_token")
	if err != nil {
		return fmt.Errorf("failed to get GitHub token from secret: %v", err)
	}

	ctx := context.Background()
	client := github.NewClient(nil).WithAuthToken(githubToken)

	// First create the issue without assignment
	julesLabel := "jules"
	issue := &github.IssueRequest{
		Title:  &title,
		Body:   &body,
		Labels: &[]string{julesLabel},
	}

	log.WithFields(log.Fields{
		"owner": owner,
		"repo":  repo,
		"title": title,
		"label": julesLabel,
	}).Info("Creating GitHub issue")

	createdIssue, _, err := client.Issues.Create(ctx, owner, repo, issue)
	if err != nil {
		return fmt.Errorf("failed to create GitHub issue: %v", err)
	}

	issueNumber := createdIssue.GetNumber()
	log.WithFields(log.Fields{
		"owner":       owner,
		"repo":        repo,
		"title":       title,
		"issueNumber": issueNumber,
		"label":       julesLabel,
	}).Info("Successfully created GitHub issue")

	// Now try to assign to copilot-swe-agent (with error handling that doesn't fail)
	copilotAssignee := "copilot-swe-agent"
	assignErr := assignIssueToCopilot(ctx, client, owner, repo, issueNumber, copilotAssignee)
	if assignErr != nil {
		log.WithFields(log.Fields{
			"owner":       owner,
			"repo":        repo,
			"issueNumber": issueNumber,
			"assignee":    copilotAssignee,
			"error":       assignErr,
		}).Warn("Failed to assign issue to copilot-swe-agent, but issue was created successfully")
	} else {
		log.WithFields(log.Fields{
			"owner":       owner,
			"repo":        repo,
			"issueNumber": issueNumber,
			"assignee":    copilotAssignee,
		}).Info("Successfully assigned issue to copilot-swe-agent")
	}

	return nil
}

// assignIssueToCopilot assigns an issue to copilot-swe-agent
func assignIssueToCopilot(ctx context.Context, client *github.Client, owner, repo string, issueNumber int, assignee string) error {
	// Try to assign the issue
	_, _, err := client.Issues.AddAssignees(ctx, owner, repo, issueNumber, []string{assignee})
	if err != nil {
		return fmt.Errorf("failed to assign issue to %s: %v", assignee, err)
	}
	return nil
}
